channels:
  - defaults
  - conda-forge
dependencies:
  - matplotlib
  - numpy
  - pandas
  - plotly
  - scikit-learn
  - statsmodels
  - streamlit
  - ta-lib
  - yfinance
  - pip
  - pip:
    - arch
name: env
