name: test_thesis
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - _openmp_mutex=4.5
  - altair=5.0.1
  - anyio=4.6.2
  - appdirs=1.4.4
  - arch-py=7.2.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow-cpp=11.0.0
  - asttokens=2.0.5
  - async-lru=2.0.4
  - attrs=24.2.0
  - aws-c-auth=0.7.4
  - aws-c-cal=0.6.2
  - aws-c-common=0.9.3
  - aws-c-compression=0.2.17
  - aws-c-event-stream=0.3.2
  - aws-c-http=0.7.13
  - aws-c-io=0.13.33
  - aws-c-mqtt=0.9.7
  - aws-c-s3=0.3.17
  - aws-c-sdkutils=0.1.12
  - aws-checksums=0.1.17
  - aws-crt-cpp=0.24.2
  - aws-sdk-cpp=1.10.57
  - babel=2.11.0
  - beautifulsoup4=4.12.3
  - blas=1.0
  - bleach=6.2.0
  - blinker=1.6.2
  - boost-cpp=1.85.0
  - bottleneck=1.4.2
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.11.26
  - cachetools=5.3.3
  - certifi=2024.8.30
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - click=8.1.7
  - colorama=0.4.6
  - comm=0.2.1
  - contourpy=1.3.1
  - cpuonly=2.0
  - cycler=0.11.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - executing=0.8.3
  - filelock=3.13.1
  - fonttools=4.51.0
  - freetype=2.12.1
  - frozendict=2.4.2
  - fsspec=2024.6.1
  - gflags=2.2.2
  - gitdb=4.0.7
  - gitpython=3.1.43
  - glib=2.82.2
  - glib-tools=2.82.2
  - gmpy2=2.1.2
  - gst-plugins-base=1.24.7
  - gstreamer=1.24.7
  - h11=0.14.0
  - html5lib=1.1
  - httpcore=1.0.2
  - httpx=0.27.0
  - icu=75.1
  - idna=3.7
  - intel-openmp=2024.2.1
  - ipykernel=6.29.5
  - ipython=8.27.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.8.1
  - jedi=0.19.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - json5=0.9.25
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.7.1
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.0
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.1
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.2.5
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=1.0.0
  - kiwisolver=1.4.4
  - krb5=1.21.3
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20230125.3
  - libarrow=11.0.0
  - libblas=3.9.0
  - libboost=1.85.0
  - libboost-devel=1.85.0
  - libboost-headers=1.85.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang13=19.1.5
  - libcrc32c=1.1.2
  - libcurl=8.10.1
  - libdeflate=1.22
  - libevent=2.1.12
  - libexpat=2.6.4
  - libffi=3.4.4
  - libgcc=14.2.0
  - libglib=2.82.2
  - libgomp=14.2.0
  - libgoogle-cloud=2.12.0
  - libgrpc=1.56.2
  - libhwloc=2.11.2
  - libiconv=1.17
  - libintl=0.22.5
  - libintl-devel=0.22.5
  - libjpeg-turbo=3.0.3
  - liblapack=3.9.0
  - liblzma=5.6.3
  - libogg=1.3.5
  - libpng=1.6.44
  - libprotobuf=4.23.3
  - libsodium=1.0.18
  - libsqlite=3.47.2
  - libssh2=1.11.1
  - libta-lib=0.4.0
  - libthrift=0.18.1
  - libtiff=4.7.0
  - libutf8proc=2.8.0
  - libuv=1.48.0
  - libvorbis=1.3.7
  - libwebp-base=1.4.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxcb=1.17.0
  - libxml2=2.13.5
  - libxslt=1.1.41
  - libzlib=1.3.1
  - lightning-utilities=0.11.9
  - lxml=5.3.0
  - lz4-c=1.9.4
  - markdown-it-py=2.2.0
  - markupsafe=2.1.3
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.6
  - mdurl=0.1.0
  - mistune=2.0.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpir=3.0.0
  - mpmath=1.3.0
  - multitasking=0.0.9
  - nbclient=0.8.0
  - nbconvert=7.16.4
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - networkx=3.2.1
  - notebook=7.2.2
  - notebook-shim=0.2.3
  - numexpr=2.8.4
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openjpeg=2.5.2
  - openssl=3.4.0
  - orc=1.9.0
  - overrides=7.4.0
  - packaging=24.1
  - pandas=2.2.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - patsy=0.5.6
  - pcre2=10.44
  - peewee=3.17.7
  - pillow=11.0.0
  - pip=24.2
  - platformdirs=3.10.0
  - plotly=5.24.1
  - ply=3.11
  - prometheus_client=0.21.0
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - protobuf=4.23.3
  - psutil=5.9.0
  - pthread-stubs=0.3
  - pure_eval=0.2.2
  - pyarrow=11.0.0
  - pycparser=2.21
  - pydeck=0.8.0
  - pygments=2.15.1
  - pyparsing=3.2.0
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.11.11
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.20.0
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytorch=2.3.1
  - pytorch-lightning=2.4.0
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pywin32=305
  - pywinpty=2.0.14
  - pyyaml=6.0.2
  - pyzmq=25.1.2
  - qt-main=5.15.15
  - re2=2023.03.02
  - referencing=0.30.2
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.9.4
  - rpds-py=0.10.6
  - scikit-learn=1.5.1
  - scipy=1.14.1
  - send2trash=1.8.2
  - setuptools=75.1.0
  - sip=6.7.12
  - six=1.16.0
  - smmap=4.0.0
  - snappy=1.1.10
  - sniffio=1.3.0
  - soupsieve=2.5
  - stack_data=0.2.0
  - statsmodels=0.14.2
  - streamlit=1.40.1
  - sympy=1.13.2
  - ta-lib=0.4.32
  - tbb=2021.13.0
  - tenacity=9.0.0
  - terminado=0.17.1
  - threadpoolctl=3.5.0
  - tinycss2=1.2.1
  - tk=8.6.13
  - toml=0.10.2
  - toolz=0.12.0
  - torchaudio=2.3.1
  - torchmetrics=1.4.0.post0
  - torchvision=0.18.1
  - tornado=6.4.1
  - tqdm=4.66.5
  - traitlets=5.14.3
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzdata=2024b
  - ucrt=10.0.20348.0
  - unicodedata2=15.1.0
  - urllib3=2.2.3
  - vc=14.40
  - vc14_runtime=14.42.34433
  - vs2015_runtime=14.42.34433
  - watchdog=4.0.1
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.44.0
  - widgetsnbextension=3.6.6
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.5
  - xz=5.4.6
  - yaml=0.2.5
  - yaml-cpp=0.8.0
  - yfinance=0.2.50
  - zeromq=4.3.5
  - zlib=1.3.1
  - zstd=1.5.6
