channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - matplotlib
  - numpy
  - pandas
  - plotly
  - scikit-learn
  - statsmodels
  - streamlit
  - ta-lib
  - yfinance
  - arch-py
  - pytorch
  - pytorch-lightning
name: env
