name: thesis
channels:
  - defaults
  - conda-forge
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.9.24
  - intel-openmp=2024.2.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.4.4
  - libhwloc=2.11.1
  - libiconv=1.17
  - liblapack=3.9.0
  - libta-lib=0.4.0
  - libxml2=2.13.1
  - mkl=2024.2.2
  - openssl=3.4.0
  - pip=24.2
  - pthreads-win32=2.9.1
  - python=3.11.10
  - python_abi=3.11
  - setuptools=75.1.0
  - sqlite=3.45.3
  - ta-lib=0.5.1
  - tbb=2021.13.0
  - tk=8.6.14
  - ucrt=10.0.22621.0
  - vc=14.40
  - vc14_runtime=14.42.34433
  - vs2015_runtime=14.42.34433
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.10.10
      - aiosignal==1.3.1
      - altair==5.5.0
      - arch==7.2.0
      - attrs==24.2.0
      - beautifulsoup4==4.12.3
      - blinker==1.9.0
      - cachetools==5.5.0
      - certifi==2024.8.30
      - charset-normalizer==3.3.2
      - click==8.1.7
      - colorama==0.4.6
      - contourpy==1.3.1
      - cycler==0.12.1
      - filelock==3.13.1
      - fonttools==4.54.1
      - frozendict==2.4.4
      - frozenlist==1.5.0
      - fsspec==2024.2.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - html5lib==1.1
      - idna==3.10
      - jinja2==3.1.3
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - kiwisolver==1.4.7
      - lightning==2.4.0
      - lightning-utilities==0.11.8
      - lxml==5.3.0
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.2
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.1.0
      - multitasking==0.0.11
      - narwhals==1.16.0
      - networkx==3.2.1
      - numpy==1.26.4
      - packaging==24.1
      - pandas==2.2.3
      - patsy==0.5.6
      - peewee==3.17.6
      - pillow==10.2.0
      - platformdirs==4.3.6
      - plotly==5.24.1
      - propcache==0.2.0
      - protobuf==5.29.1
      - pyarrow==18.1.0
      - pydeck==0.9.1
      - pygments==2.18.0
      - pyparsing==3.2.0
      - python-dateutil==2.9.0
      - pytorch-lightning==2.4.0
      - pytz==2024.1
      - pyyaml==6.0.2
      - referencing==0.35.1
      - requests==2.32.3
      - rich==13.9.4
      - rpds-py==0.22.3
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - six==1.16.0
      - smmap==5.0.1
      - soupsieve==2.6
      - statsmodels==0.14.4
      - streamlit==1.40.2
      - sympy==1.13.1
      - tenacity==9.0.0
      - threadpoolctl==3.5.0
      - toml==0.10.2
      - torch==2.5.1
      - torchaudio==2.5.1
      - torchmetrics==1.5.2
      - torchvision==0.20.1
      - tornado==6.4.2
      - tqdm==4.67.0
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - urllib3==2.2.3
      - watchdog==6.0.0
      - webencodings==0.5.1
      - xgboost==2.1.1
      - yarl==1.17.1
      - yfinance==0.2.44
