channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
- matplotlib
- numpy
- pandas
- plotly
- pytorch-lightning
- scikit-learn
- statsmodels
- streamlit
- ta-lib
- torchaudio
- torchvision
- yfinance
- pip
- pip:
  - arch
  - torch
name: env